codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
ignore:
  - "app/src/main/java/com/edipasquale/bitrise/App.kt"
  - "app/src/main/java/com/edipasquale/bitrise/dto/core/Either.kt"
  - "app/src/main/java/com/edipasquale/bitrise/koin/AppInjector.kt"
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no